CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Currencies" (
    "Id" uuid NOT NULL,
    "Code" character varying(3) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Symbol" character varying(10) NOT NULL,
    "DecimalPlaces" integer NOT NULL DEFAULT 2,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionPlans" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Type" integer NOT NULL,
    "MonthlyPrice" numeric(18,4) NOT NULL,
    "AnnualPrice" numeric(18,4) NOT NULL,
    "MaxProducts" integer,
    "MaxUsers" integer,
    "MaxWarehouses" integer,
    "MaxTransactionsPerMonth" integer,
    "Features" jsonb NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ActivityLogs" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Activity" text NOT NULL,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "AvatarUrl" character varying(500),
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "LastLoginAt" timestamp with time zone,
    "Preferences" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedBy" uuid,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" uuid,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" character varying(500) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByToken" character varying(500),
    "DeviceInfo" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "UserName" text NOT NULL,
    "Action" text NOT NULL,
    "EntityType" text NOT NULL,
    "EntityId" text,
    "OldValues" text,
    "NewValues" text,
    "IpAddress" text,
    "UserAgent" text,
    "Timestamp" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "BatchLots" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "BatchNumber" text NOT NULL,
    "LotNumber" text,
    "ManufactureDate" date,
    "ExpiryDate" date,
    "Quantity" integer NOT NULL,
    "RemainingQuantity" integer NOT NULL,
    "CostPrice" numeric,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_BatchLots" PRIMARY KEY ("Id")
);

CREATE TABLE "BillingHistories" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "SubscriptionId" uuid NOT NULL,
    "Amount" numeric NOT NULL,
    "Currency" text NOT NULL,
    "Status" text NOT NULL,
    "InvoiceUrl" text,
    "StripeInvoiceId" text,
    "PaidAt" timestamp with time zone,
    "PeriodStart" timestamp with time zone,
    "PeriodEnd" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_BillingHistories" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(200),
    "Description" text,
    "ImageUrl" character varying(500),
    "ParentCategoryId" uuid,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Coupons" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Code" text NOT NULL,
    "DiscountId" uuid NOT NULL,
    "MaxUses" integer,
    "UsedCount" integer NOT NULL,
    "MaxUsesPerCustomer" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
);

CREATE TABLE "CustomerGroups" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" text NOT NULL,
    "DiscountPercent" numeric NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_CustomerGroups" PRIMARY KEY ("Id")
);

CREATE TABLE "Customers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CustomerGroupId" uuid,
    "Name" character varying(300) NOT NULL,
    "Code" character varying(50),
    "Email" character varying(255),
    "Phone" character varying(20),
    "AlternatePhone" character varying(20),
    "Address_Street" character varying(500),
    "Address_Street2" character varying(500),
    "Address_City" character varying(100),
    "Address_State" character varying(100),
    "Address_PostalCode" character varying(20),
    "Address_Country" character varying(100),
    "TaxIdentificationNo" character varying(100),
    "CreditLimit" numeric(18,4),
    "CurrentBalance" numeric(18,4) NOT NULL DEFAULT 0.0,
    "LoyaltyPoints" integer NOT NULL DEFAULT 0,
    "TotalPurchases" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TotalOrders" integer NOT NULL DEFAULT 0,
    "DateOfBirth" date,
    "Notes" text,
    "Tags" text[],
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customers_CustomerGroups_CustomerGroupId" FOREIGN KEY ("CustomerGroupId") REFERENCES "CustomerGroups" ("Id") ON DELETE SET NULL
);

CREATE TABLE "LoyaltyTransactions" (
    "Id" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    "Points" integer NOT NULL,
    "Type" text NOT NULL,
    "ReferenceId" uuid,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_LoyaltyTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LoyaltyTransactions_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Discounts" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Type" integer NOT NULL,
    "Value" numeric NOT NULL,
    "MinOrderAmount" numeric,
    "MaxDiscountAmount" numeric,
    "ApplicableToAll" boolean NOT NULL,
    "CategoryIds" uuid[],
    "ProductIds" uuid[],
    "CustomerGroupIds" uuid[],
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Discounts" PRIMARY KEY ("Id")
);

CREATE TABLE "ExchangeRates" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "BaseCurrencyId" uuid NOT NULL,
    "TargetCurrencyId" uuid NOT NULL,
    "Rate" numeric(18,8) NOT NULL,
    "EffectiveDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ExchangeRates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExchangeRates_Currencies_BaseCurrencyId" FOREIGN KEY ("BaseCurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ExchangeRates_Currencies_TargetCurrencyId" FOREIGN KEY ("TargetCurrencyId") REFERENCES "Currencies" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "GoodsReceivedNoteItems" (
    "Id" uuid NOT NULL,
    "GoodsReceivedNoteId" uuid NOT NULL,
    "PurchaseOrderItemId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "QuantityReceived" integer NOT NULL,
    "QuantityAccepted" integer NOT NULL,
    "QuantityRejected" integer NOT NULL,
    "RejectionReason" text,
    "BatchLotId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_GoodsReceivedNoteItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GoodsReceivedNoteItems_BatchLots_BatchLotId" FOREIGN KEY ("BatchLotId") REFERENCES "BatchLots" ("Id")
);

CREATE TABLE "GoodsReceivedNotes" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "PurchaseOrderId" uuid NOT NULL,
    "GrnNumber" text NOT NULL,
    "ReceivedDate" timestamp with time zone NOT NULL,
    "ReceivedBy" uuid NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_GoodsReceivedNotes" PRIMARY KEY ("Id")
);

CREATE TABLE "HeldTransactions" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CustomerId" uuid,
    "ReferenceNote" text,
    "ItemsJson" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "CashierId" uuid NOT NULL,
    "HeldAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_HeldTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HeldTransactions_AspNetUsers_CashierId" FOREIGN KEY ("CashierId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HeldTransactions_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id")
);

CREATE TABLE "InventoryTransactions" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "WarehouseId" uuid NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitCost" numeric,
    "TotalCost" numeric,
    "RunningBalance" integer NOT NULL,
    "ReferenceType" text,
    "ReferenceId" uuid,
    "BatchLotId" uuid,
    "Notes" text,
    "Reason" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryTransactions_BatchLots_BatchLotId" FOREIGN KEY ("BatchLotId") REFERENCES "BatchLots" ("Id")
);

CREATE TABLE "InvoiceSettings" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Prefix" text NOT NULL,
    "NextNumber" integer NOT NULL,
    "Template" text NOT NULL,
    "ShowLogo" boolean NOT NULL,
    "ShowTaxBreakdown" boolean NOT NULL,
    "FooterText" text,
    "TermsAndConditions" text,
    "BankDetails" text,
    "CustomCss" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_InvoiceSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "UserId" uuid,
    "Type" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Data" text,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "SaleId" uuid,
    "PurchaseOrderId" uuid,
    "PaymentMethod" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Status" integer NOT NULL,
    "TransactionReference" text,
    "Notes" text,
    "ProcessedBy" uuid NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductImages" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Url" text NOT NULL,
    "AltText" text,
    "SortOrder" integer NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CategoryId" uuid,
    "UnitOfMeasureId" uuid,
    "Name" character varying(300) NOT NULL,
    "Slug" character varying(300),
    "SKU" character varying(100) NOT NULL,
    "Barcode" character varying(100),
    "Description" text,
    "ShortDescription" character varying(500),
    "CostPrice" numeric(18,4) NOT NULL DEFAULT 0.0,
    "SellingPrice" numeric(18,4) NOT NULL DEFAULT 0.0,
    "WholesalePrice" numeric(18,4),
    "MinimumPrice" numeric(18,4),
    "TaxConfigurationId" uuid,
    "ReorderLevel" integer NOT NULL,
    "ReorderQuantity" integer NOT NULL,
    "MaxStockLevel" integer,
    "Weight" numeric(10,3),
    "Dimensions" text,
    "Tags" text[],
    "CustomFields" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "IsService" boolean NOT NULL,
    "TrackInventory" boolean NOT NULL DEFAULT TRUE,
    "AllowNegativeStock" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL
);

CREATE TABLE "ProductVariants" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Name" text NOT NULL,
    "SKU" text NOT NULL,
    "Barcode" text,
    "AdditionalCost" numeric NOT NULL,
    "AdditionalPrice" numeric NOT NULL,
    "Attributes" text NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PurchaseOrderItems" (
    "Id" uuid NOT NULL,
    "PurchaseOrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "Quantity" integer NOT NULL,
    "ReceivedQuantity" integer NOT NULL,
    "UnitCost" numeric NOT NULL,
    "TaxRate" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "DiscountPercent" numeric NOT NULL,
    "LineTotal" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_PurchaseOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseOrderItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
    CONSTRAINT "FK_PurchaseOrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PurchaseOrders" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "SupplierId" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "OrderNumber" character varying(50) NOT NULL,
    "Status" integer NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ExpectedDeliveryDate" timestamp with time zone,
    "SubTotal" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TaxAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "ShippingCost" numeric(18,4) NOT NULL DEFAULT 0.0,
    "DiscountAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "PaidAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "Notes" text,
    "InternalNotes" text,
    "RequestedBy" uuid NOT NULL,
    "ApprovedBy" uuid,
    "ApprovedAt" timestamp with time zone,
    "CancelledBy" uuid,
    "CancelledAt" timestamp with time zone,
    "CancellationReason" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("Id")
);

CREATE TABLE "PurchaseReturnItems" (
    "Id" uuid NOT NULL,
    "PurchaseReturnId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "Quantity" integer NOT NULL,
    "UnitCost" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Reason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_PurchaseReturnItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseReturnItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
    CONSTRAINT "FK_PurchaseReturnItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PurchaseReturns" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "PurchaseOrderId" uuid NOT NULL,
    "SupplierId" uuid NOT NULL,
    "ReturnNumber" text NOT NULL,
    "ReturnDate" timestamp with time zone NOT NULL,
    "Reason" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_PurchaseReturns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseReturns_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "QuotationItems" (
    "Id" uuid NOT NULL,
    "QuotationId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "DiscountPercent" numeric NOT NULL,
    "TaxRate" numeric NOT NULL,
    "LineTotal" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_QuotationItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuotationItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
    CONSTRAINT "FK_QuotationItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Quotations" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CustomerId" uuid,
    "QuotationNumber" text NOT NULL,
    "Status" integer NOT NULL,
    "SubTotal" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "DiscountAmount" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "ValidUntil" timestamp with time zone,
    "Notes" text,
    "ConvertedToSaleId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Quotations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Quotations_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id")
);

CREATE TABLE "SaleItems" (
    "Id" uuid NOT NULL,
    "SaleId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "ProductName" character varying(300) NOT NULL,
    "SKU" character varying(100) NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,4) NOT NULL,
    "CostPrice" numeric(18,4) NOT NULL,
    "DiscountPercent" numeric(5,2) NOT NULL DEFAULT 0.0,
    "DiscountAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TaxRate" numeric(5,2) NOT NULL DEFAULT 0.0,
    "TaxAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "LineTotal" numeric(18,4) NOT NULL,
    "BatchLotId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaleItems_BatchLots_BatchLotId" FOREIGN KEY ("BatchLotId") REFERENCES "BatchLots" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SaleItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SaleItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SaleReturnItems" (
    "Id" uuid NOT NULL,
    "SaleReturnId" uuid NOT NULL,
    "SaleItemId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "RefundAmount" numeric NOT NULL,
    "ReturnToStock" boolean NOT NULL,
    "WarehouseId" uuid,
    "Reason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SaleReturnItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaleReturnItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SaleReturnItems_SaleItems_SaleItemId" FOREIGN KEY ("SaleItemId") REFERENCES "SaleItems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SaleReturns" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "SaleId" uuid NOT NULL,
    "ReturnNumber" text NOT NULL,
    "Reason" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "TotalRefundAmount" numeric NOT NULL,
    "RefundMethod" integer NOT NULL,
    "Status" integer NOT NULL,
    "ProcessedBy" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SaleReturns" PRIMARY KEY ("Id")
);

CREATE TABLE "Sales" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "CustomerId" uuid,
    "WarehouseId" uuid NOT NULL,
    "QuotationId" uuid,
    "InvoiceNumber" character varying(50) NOT NULL,
    "Status" integer NOT NULL,
    "SubTotal" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TaxAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "DiscountAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "ShippingAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "TotalAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "PaidAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "ChangeAmount" numeric(18,4) NOT NULL DEFAULT 0.0,
    "DiscountId" uuid,
    "CouponId" uuid,
    "CouponCode" character varying(50),
    "LoyaltyPointsEarned" integer NOT NULL,
    "LoyaltyPointsRedeemed" integer NOT NULL,
    "Notes" text,
    "InternalNotes" text,
    "CashierId" uuid NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_AspNetUsers_CashierId" FOREIGN KEY ("CashierId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Sales_Coupons_CouponId" FOREIGN KEY ("CouponId") REFERENCES "Coupons" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sales_Discounts_DiscountId" FOREIGN KEY ("DiscountId") REFERENCES "Discounts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Sales_Quotations_QuotationId" FOREIGN KEY ("QuotationId") REFERENCES "Quotations" ("Id") ON DELETE SET NULL
);

CREATE TABLE "StockAdjustmentItems" (
    "Id" uuid NOT NULL,
    "StockAdjustmentId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "QuantityBefore" integer NOT NULL,
    "QuantityAfter" integer NOT NULL,
    "QuantityAdjusted" integer NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StockAdjustmentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockAdjustmentItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
    CONSTRAINT "FK_StockAdjustmentItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StockAdjustments" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "AdjustmentNumber" text NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "Reason" integer NOT NULL,
    "Notes" text,
    "AdjustedBy" uuid NOT NULL,
    "AdjustmentDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StockAdjustments" PRIMARY KEY ("Id")
);

CREATE TABLE "StockLevels" (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "WarehouseId" uuid NOT NULL,
    "WarehouseZoneId" uuid,
    "Quantity" integer NOT NULL DEFAULT 0,
    "ReservedQuantity" integer NOT NULL DEFAULT 0,
    "LastStockTakeDate" timestamp with time zone,
    "LastUpdated" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StockLevels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockLevels_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StockLevels_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StockTransferItems" (
    "Id" uuid NOT NULL,
    "StockTransferId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "Quantity" integer NOT NULL,
    "ReceivedQuantity" integer,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StockTransferItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockTransferItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id"),
    CONSTRAINT "FK_StockTransferItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StockTransfers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "TransferNumber" text NOT NULL,
    "FromWarehouseId" uuid NOT NULL,
    "ToWarehouseId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "Notes" text,
    "TransferredBy" uuid NOT NULL,
    "ReceivedBy" uuid,
    "TransferDate" timestamp with time zone NOT NULL,
    "ReceivedDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StockTransfers" PRIMARY KEY ("Id")
);

CREATE TABLE "Subscriptions" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "PlanId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "BillingCycle" character varying(20) NOT NULL DEFAULT 'monthly',
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "TrialEndsAt" timestamp with time zone,
    "CancelledAt" timestamp with time zone,
    "CancellationReason" text,
    "StripeCustomerId" character varying(255),
    "StripeSubscriptionId" character varying(255),
    "CurrentPeriodStart" timestamp with time zone,
    "CurrentPeriodEnd" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SupplierProducts" (
    "Id" uuid NOT NULL,
    "SupplierId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "SupplierSKU" text,
    "UnitCost" numeric NOT NULL,
    "MinOrderQuantity" integer NOT NULL,
    "LeadTimeDays" integer,
    "IsPreferred" boolean NOT NULL,
    "LastPurchaseDate" timestamp with time zone,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SupplierProducts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupplierProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Suppliers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" character varying(300) NOT NULL,
    "Code" character varying(50),
    "ContactPerson" character varying(200),
    "Email" character varying(255),
    "Phone" character varying(20),
    "AlternatePhone" character varying(20),
    "TaxIdentificationNo" character varying(100),
    "Website" character varying(255),
    "Address_Street" character varying(500),
    "Address_Street2" character varying(500),
    "Address_City" character varying(100),
    "Address_State" character varying(100),
    "Address_PostalCode" character varying(20),
    "Address_Country" character varying(100),
    "PaymentTerms" character varying(200),
    "CreditLimit" numeric(18,4),
    "CurrentBalance" numeric(18,4) NOT NULL DEFAULT 0.0,
    "BankDetails" text,
    "Rating" numeric(3,2),
    "Notes" text,
    "Tags" text[],
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);

CREATE TABLE "SystemSettings" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Key" text NOT NULL,
    "Value" text NOT NULL,
    "Category" text,
    "DataType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "TaxConfigurations" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Rate" numeric NOT NULL,
    "TaxNumber" text,
    "IsCompound" boolean NOT NULL,
    "IsInclusive" boolean NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_TaxConfigurations" PRIMARY KEY ("Id")
);

CREATE TABLE "TaxGroups" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" text NOT NULL,
    "TaxConfigurationIds" uuid[] NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_TaxGroups" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenants" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Subdomain" character varying(100) NOT NULL,
    "CustomDomain" character varying(255),
    "LogoUrl" character varying(500),
    "FaviconUrl" character varying(500),
    "PrimaryColor" character varying(7) NOT NULL DEFAULT '#1976D2',
    "SecondaryColor" character varying(7) NOT NULL DEFAULT '#424242',
    "BusinessType" character varying(100),
    "BusinessRegistrationNo" character varying(100),
    "TaxIdentificationNo" character varying(100),
    "Phone" character varying(20),
    "Email" character varying(255),
    "Website" character varying(255),
    "Address_Street" character varying(500),
    "Address_Street2" character varying(500),
    "Address_City" character varying(100),
    "Address_State" character varying(100),
    "Address_PostalCode" character varying(20),
    "Address_Country" character varying(100),
    "DefaultCurrencyId" uuid,
    "DefaultWarehouseId" uuid,
    "ValuationMethod" integer NOT NULL DEFAULT 2,
    "FinancialYearStart" integer NOT NULL DEFAULT 1,
    "TimeZone" character varying(100) NOT NULL DEFAULT 'UTC',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DefaultWarehouseId1" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tenants_Currencies_DefaultCurrencyId" FOREIGN KEY ("DefaultCurrencyId") REFERENCES "Currencies" ("Id") ON DELETE SET NULL
);

CREATE TABLE "UnitsOfMeasure" (
    "Id" uuid NOT NULL,
    "TenantId" uuid,
    "Name" text NOT NULL,
    "Abbreviation" text NOT NULL,
    "IsSystemDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_UnitsOfMeasure" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UnitsOfMeasure_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "Warehouses" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Code" character varying(50),
    "Address_Street" character varying(500),
    "Address_Street2" character varying(500),
    "Address_City" character varying(100),
    "Address_State" character varying(100),
    "Address_PostalCode" character varying(20),
    "Address_Country" character varying(100),
    "ManagerId" uuid,
    "Phone" character varying(20),
    "Email" character varying(255),
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Warehouses_AspNetUsers_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Warehouses_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WarehouseZones" (
    "Id" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Code" text,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_WarehouseZones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WarehouseZones_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ActivityLogs_TenantId" ON "ActivityLogs" ("TenantId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_TenantId" ON "AspNetUsers" ("TenantId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_AuditLogs_TenantId" ON "AuditLogs" ("TenantId");

CREATE INDEX "IX_BatchLots_ProductId" ON "BatchLots" ("ProductId");

CREATE INDEX "IX_BatchLots_TenantId" ON "BatchLots" ("TenantId");

CREATE INDEX "IX_BillingHistories_SubscriptionId" ON "BillingHistories" ("SubscriptionId");

CREATE INDEX "IX_BillingHistories_TenantId" ON "BillingHistories" ("TenantId");

CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");

CREATE INDEX "IX_Categories_TenantId" ON "Categories" ("TenantId");

CREATE INDEX "IX_Coupons_DiscountId" ON "Coupons" ("DiscountId");

CREATE INDEX "IX_Coupons_TenantId" ON "Coupons" ("TenantId");

CREATE UNIQUE INDEX "IX_Currencies_Code" ON "Currencies" ("Code");

CREATE INDEX "IX_CustomerGroups_TenantId" ON "CustomerGroups" ("TenantId");

CREATE INDEX "IX_Customers_CustomerGroupId" ON "Customers" ("CustomerGroupId");

CREATE INDEX "IX_Customers_TenantId" ON "Customers" ("TenantId");

CREATE INDEX "IX_Customers_TenantId_Email" ON "Customers" ("TenantId", "Email");

CREATE INDEX "IX_Customers_TenantId_Phone" ON "Customers" ("TenantId", "Phone");

CREATE INDEX "IX_Discounts_TenantId" ON "Discounts" ("TenantId");

CREATE INDEX "IX_ExchangeRates_BaseCurrencyId" ON "ExchangeRates" ("BaseCurrencyId");

CREATE INDEX "IX_ExchangeRates_TargetCurrencyId" ON "ExchangeRates" ("TargetCurrencyId");

CREATE UNIQUE INDEX "IX_ExchangeRates_TenantId_BaseCurrencyId_TargetCurrencyId_Effe~" ON "ExchangeRates" ("TenantId", "BaseCurrencyId", "TargetCurrencyId", "EffectiveDate");

CREATE INDEX "IX_GoodsReceivedNoteItems_BatchLotId" ON "GoodsReceivedNoteItems" ("BatchLotId");

CREATE INDEX "IX_GoodsReceivedNoteItems_GoodsReceivedNoteId" ON "GoodsReceivedNoteItems" ("GoodsReceivedNoteId");

CREATE INDEX "IX_GoodsReceivedNoteItems_ProductId" ON "GoodsReceivedNoteItems" ("ProductId");

CREATE INDEX "IX_GoodsReceivedNoteItems_PurchaseOrderItemId" ON "GoodsReceivedNoteItems" ("PurchaseOrderItemId");

CREATE INDEX "IX_GoodsReceivedNotes_PurchaseOrderId" ON "GoodsReceivedNotes" ("PurchaseOrderId");

CREATE INDEX "IX_GoodsReceivedNotes_TenantId" ON "GoodsReceivedNotes" ("TenantId");

CREATE INDEX "IX_HeldTransactions_CashierId" ON "HeldTransactions" ("CashierId");

CREATE INDEX "IX_HeldTransactions_CustomerId" ON "HeldTransactions" ("CustomerId");

CREATE INDEX "IX_HeldTransactions_TenantId" ON "HeldTransactions" ("TenantId");

CREATE INDEX "IX_InventoryTransactions_BatchLotId" ON "InventoryTransactions" ("BatchLotId");

CREATE INDEX "IX_InventoryTransactions_ProductId" ON "InventoryTransactions" ("ProductId");

CREATE INDEX "IX_InventoryTransactions_ProductVariantId" ON "InventoryTransactions" ("ProductVariantId");

CREATE INDEX "IX_InventoryTransactions_TenantId" ON "InventoryTransactions" ("TenantId");

CREATE INDEX "IX_InventoryTransactions_WarehouseId" ON "InventoryTransactions" ("WarehouseId");

CREATE INDEX "IX_InvoiceSettings_TenantId" ON "InvoiceSettings" ("TenantId");

CREATE INDEX "IX_LoyaltyTransactions_CustomerId" ON "LoyaltyTransactions" ("CustomerId");

CREATE INDEX "IX_Notifications_TenantId" ON "Notifications" ("TenantId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_Payments_PurchaseOrderId" ON "Payments" ("PurchaseOrderId");

CREATE INDEX "IX_Payments_SaleId" ON "Payments" ("SaleId");

CREATE INDEX "IX_Payments_TenantId" ON "Payments" ("TenantId");

CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE INDEX "IX_Products_TaxConfigurationId" ON "Products" ("TaxConfigurationId");

CREATE INDEX "IX_Products_TenantId_Barcode" ON "Products" ("TenantId", "Barcode");

CREATE INDEX "IX_Products_TenantId_CategoryId" ON "Products" ("TenantId", "CategoryId");

CREATE UNIQUE INDEX "IX_Products_TenantId_SKU" ON "Products" ("TenantId", "SKU") WHERE "IsDeleted" = false;

CREATE INDEX "IX_Products_UnitOfMeasureId" ON "Products" ("UnitOfMeasureId");

CREATE INDEX "IX_ProductVariants_ProductId" ON "ProductVariants" ("ProductId");

CREATE INDEX "IX_PurchaseOrderItems_ProductId" ON "PurchaseOrderItems" ("ProductId");

CREATE INDEX "IX_PurchaseOrderItems_ProductVariantId" ON "PurchaseOrderItems" ("ProductVariantId");

CREATE INDEX "IX_PurchaseOrderItems_PurchaseOrderId" ON "PurchaseOrderItems" ("PurchaseOrderId");

CREATE INDEX "IX_PurchaseOrders_SupplierId" ON "PurchaseOrders" ("SupplierId");

CREATE UNIQUE INDEX "IX_PurchaseOrders_TenantId_OrderNumber" ON "PurchaseOrders" ("TenantId", "OrderNumber");

CREATE INDEX "IX_PurchaseOrders_TenantId_Status" ON "PurchaseOrders" ("TenantId", "Status");

CREATE INDEX "IX_PurchaseOrders_WarehouseId" ON "PurchaseOrders" ("WarehouseId");

CREATE INDEX "IX_PurchaseReturnItems_ProductId" ON "PurchaseReturnItems" ("ProductId");

CREATE INDEX "IX_PurchaseReturnItems_ProductVariantId" ON "PurchaseReturnItems" ("ProductVariantId");

CREATE INDEX "IX_PurchaseReturnItems_PurchaseReturnId" ON "PurchaseReturnItems" ("PurchaseReturnId");

CREATE INDEX "IX_PurchaseReturns_PurchaseOrderId" ON "PurchaseReturns" ("PurchaseOrderId");

CREATE INDEX "IX_PurchaseReturns_SupplierId" ON "PurchaseReturns" ("SupplierId");

CREATE INDEX "IX_PurchaseReturns_TenantId" ON "PurchaseReturns" ("TenantId");

CREATE INDEX "IX_QuotationItems_ProductId" ON "QuotationItems" ("ProductId");

CREATE INDEX "IX_QuotationItems_ProductVariantId" ON "QuotationItems" ("ProductVariantId");

CREATE INDEX "IX_QuotationItems_QuotationId" ON "QuotationItems" ("QuotationId");

CREATE INDEX "IX_Quotations_CustomerId" ON "Quotations" ("CustomerId");

CREATE INDEX "IX_Quotations_TenantId" ON "Quotations" ("TenantId");

CREATE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_SaleItems_BatchLotId" ON "SaleItems" ("BatchLotId");

CREATE INDEX "IX_SaleItems_ProductId" ON "SaleItems" ("ProductId");

CREATE INDEX "IX_SaleItems_ProductVariantId" ON "SaleItems" ("ProductVariantId");

CREATE INDEX "IX_SaleItems_SaleId" ON "SaleItems" ("SaleId");

CREATE INDEX "IX_SaleReturnItems_ProductId" ON "SaleReturnItems" ("ProductId");

CREATE INDEX "IX_SaleReturnItems_SaleItemId" ON "SaleReturnItems" ("SaleItemId");

CREATE INDEX "IX_SaleReturnItems_SaleReturnId" ON "SaleReturnItems" ("SaleReturnId");

CREATE INDEX "IX_SaleReturnItems_WarehouseId" ON "SaleReturnItems" ("WarehouseId");

CREATE INDEX "IX_SaleReturns_SaleId" ON "SaleReturns" ("SaleId");

CREATE INDEX "IX_SaleReturns_TenantId" ON "SaleReturns" ("TenantId");

CREATE INDEX "IX_Sales_CashierId" ON "Sales" ("CashierId");

CREATE INDEX "IX_Sales_CouponId" ON "Sales" ("CouponId");

CREATE INDEX "IX_Sales_CustomerId" ON "Sales" ("CustomerId");

CREATE INDEX "IX_Sales_DiscountId" ON "Sales" ("DiscountId");

CREATE UNIQUE INDEX "IX_Sales_QuotationId" ON "Sales" ("QuotationId");

CREATE INDEX "IX_Sales_TenantId_CashierId" ON "Sales" ("TenantId", "CashierId");

CREATE INDEX "IX_Sales_TenantId_CustomerId" ON "Sales" ("TenantId", "CustomerId");

CREATE UNIQUE INDEX "IX_Sales_TenantId_InvoiceNumber" ON "Sales" ("TenantId", "InvoiceNumber");

CREATE INDEX "IX_Sales_TenantId_SaleDate" ON "Sales" ("TenantId", "SaleDate");

CREATE INDEX "IX_Sales_WarehouseId" ON "Sales" ("WarehouseId");

CREATE INDEX "IX_StockAdjustmentItems_ProductId" ON "StockAdjustmentItems" ("ProductId");

CREATE INDEX "IX_StockAdjustmentItems_ProductVariantId" ON "StockAdjustmentItems" ("ProductVariantId");

CREATE INDEX "IX_StockAdjustmentItems_StockAdjustmentId" ON "StockAdjustmentItems" ("StockAdjustmentId");

CREATE INDEX "IX_StockAdjustments_TenantId" ON "StockAdjustments" ("TenantId");

CREATE INDEX "IX_StockAdjustments_WarehouseId" ON "StockAdjustments" ("WarehouseId");

CREATE UNIQUE INDEX "IX_StockLevels_ProductId_ProductVariantId_WarehouseId" ON "StockLevels" ("ProductId", "ProductVariantId", "WarehouseId");

CREATE INDEX "IX_StockLevels_ProductVariantId" ON "StockLevels" ("ProductVariantId");

CREATE INDEX "IX_StockLevels_WarehouseId" ON "StockLevels" ("WarehouseId");

CREATE INDEX "IX_StockLevels_WarehouseZoneId" ON "StockLevels" ("WarehouseZoneId");

CREATE INDEX "IX_StockTransferItems_ProductId" ON "StockTransferItems" ("ProductId");

CREATE INDEX "IX_StockTransferItems_ProductVariantId" ON "StockTransferItems" ("ProductVariantId");

CREATE INDEX "IX_StockTransferItems_StockTransferId" ON "StockTransferItems" ("StockTransferId");

CREATE INDEX "IX_StockTransfers_FromWarehouseId" ON "StockTransfers" ("FromWarehouseId");

CREATE INDEX "IX_StockTransfers_TenantId" ON "StockTransfers" ("TenantId");

CREATE INDEX "IX_StockTransfers_ToWarehouseId" ON "StockTransfers" ("ToWarehouseId");

CREATE INDEX "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");

CREATE INDEX "IX_Subscriptions_TenantId" ON "Subscriptions" ("TenantId");

CREATE INDEX "IX_SupplierProducts_ProductId" ON "SupplierProducts" ("ProductId");

CREATE INDEX "IX_SupplierProducts_SupplierId" ON "SupplierProducts" ("SupplierId");

CREATE INDEX "IX_Suppliers_TenantId" ON "Suppliers" ("TenantId");

CREATE INDEX "IX_SystemSettings_TenantId" ON "SystemSettings" ("TenantId");

CREATE INDEX "IX_TaxConfigurations_TenantId" ON "TaxConfigurations" ("TenantId");

CREATE INDEX "IX_TaxGroups_TenantId" ON "TaxGroups" ("TenantId");

CREATE UNIQUE INDEX "IX_Tenants_CustomDomain" ON "Tenants" ("CustomDomain") WHERE "CustomDomain" IS NOT NULL;

CREATE INDEX "IX_Tenants_DefaultCurrencyId" ON "Tenants" ("DefaultCurrencyId");

CREATE INDEX "IX_Tenants_DefaultWarehouseId1" ON "Tenants" ("DefaultWarehouseId1");

CREATE UNIQUE INDEX "IX_Tenants_Subdomain" ON "Tenants" ("Subdomain");

CREATE INDEX "IX_UnitsOfMeasure_TenantId" ON "UnitsOfMeasure" ("TenantId");

CREATE INDEX "IX_Warehouses_ManagerId" ON "Warehouses" ("ManagerId");

CREATE INDEX "IX_Warehouses_TenantId" ON "Warehouses" ("TenantId");

CREATE INDEX "IX_WarehouseZones_WarehouseId" ON "WarehouseZones" ("WarehouseId");

ALTER TABLE "ActivityLogs" ADD CONSTRAINT "FK_ActivityLogs_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "BatchLots" ADD CONSTRAINT "FK_BatchLots_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;

ALTER TABLE "BatchLots" ADD CONSTRAINT "FK_BatchLots_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "BillingHistories" ADD CONSTRAINT "FK_BillingHistories_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id") ON DELETE CASCADE;

ALTER TABLE "BillingHistories" ADD CONSTRAINT "FK_BillingHistories_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Coupons" ADD CONSTRAINT "FK_Coupons_Discounts_DiscountId" FOREIGN KEY ("DiscountId") REFERENCES "Discounts" ("Id") ON DELETE CASCADE;

ALTER TABLE "Coupons" ADD CONSTRAINT "FK_Coupons_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "CustomerGroups" ADD CONSTRAINT "FK_CustomerGroups_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Customers" ADD CONSTRAINT "FK_Customers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Discounts" ADD CONSTRAINT "FK_Discounts_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "ExchangeRates" ADD CONSTRAINT "FK_ExchangeRates_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "GoodsReceivedNoteItems" ADD CONSTRAINT "FK_GoodsReceivedNoteItems_GoodsReceivedNotes_GoodsReceivedNote~" FOREIGN KEY ("GoodsReceivedNoteId") REFERENCES "GoodsReceivedNotes" ("Id") ON DELETE CASCADE;

ALTER TABLE "GoodsReceivedNoteItems" ADD CONSTRAINT "FK_GoodsReceivedNoteItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;

ALTER TABLE "GoodsReceivedNoteItems" ADD CONSTRAINT "FK_GoodsReceivedNoteItems_PurchaseOrderItems_PurchaseOrderItem~" FOREIGN KEY ("PurchaseOrderItemId") REFERENCES "PurchaseOrderItems" ("Id") ON DELETE CASCADE;

ALTER TABLE "GoodsReceivedNotes" ADD CONSTRAINT "FK_GoodsReceivedNotes_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "GoodsReceivedNotes" ADD CONSTRAINT "FK_GoodsReceivedNotes_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "HeldTransactions" ADD CONSTRAINT "FK_HeldTransactions_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_InventoryTransactions_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id");

ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_InventoryTransactions_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;

ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_InventoryTransactions_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "InventoryTransactions" ADD CONSTRAINT "FK_InventoryTransactions_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE;

ALTER TABLE "InvoiceSettings" ADD CONSTRAINT "FK_InvoiceSettings_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Notifications" ADD CONSTRAINT "FK_Notifications_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Payments" ADD CONSTRAINT "FK_Payments_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "Payments" ADD CONSTRAINT "FK_Payments_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE;

ALTER TABLE "Payments" ADD CONSTRAINT "FK_Payments_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "ProductImages" ADD CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_TaxConfigurations_TaxConfigurationId" FOREIGN KEY ("TaxConfigurationId") REFERENCES "TaxConfigurations" ("Id") ON DELETE SET NULL;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_UnitsOfMeasure_UnitOfMeasureId" FOREIGN KEY ("UnitOfMeasureId") REFERENCES "UnitsOfMeasure" ("Id") ON DELETE SET NULL;

ALTER TABLE "PurchaseOrderItems" ADD CONSTRAINT "FK_PurchaseOrderItems_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "PurchaseOrders" ADD CONSTRAINT "FK_PurchaseOrders_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "PurchaseOrders" ADD CONSTRAINT "FK_PurchaseOrders_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "PurchaseOrders" ADD CONSTRAINT "FK_PurchaseOrders_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT;

ALTER TABLE "PurchaseReturnItems" ADD CONSTRAINT "FK_PurchaseReturnItems_PurchaseReturns_PurchaseReturnId" FOREIGN KEY ("PurchaseReturnId") REFERENCES "PurchaseReturns" ("Id") ON DELETE CASCADE;

ALTER TABLE "PurchaseReturns" ADD CONSTRAINT "FK_PurchaseReturns_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE;

ALTER TABLE "PurchaseReturns" ADD CONSTRAINT "FK_PurchaseReturns_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "QuotationItems" ADD CONSTRAINT "FK_QuotationItems_Quotations_QuotationId" FOREIGN KEY ("QuotationId") REFERENCES "Quotations" ("Id") ON DELETE CASCADE;

ALTER TABLE "Quotations" ADD CONSTRAINT "FK_Quotations_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "SaleItems" ADD CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE;

ALTER TABLE "SaleReturnItems" ADD CONSTRAINT "FK_SaleReturnItems_SaleReturns_SaleReturnId" FOREIGN KEY ("SaleReturnId") REFERENCES "SaleReturns" ("Id") ON DELETE CASCADE;

ALTER TABLE "SaleReturnItems" ADD CONSTRAINT "FK_SaleReturnItems_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id");

ALTER TABLE "SaleReturns" ADD CONSTRAINT "FK_SaleReturns_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES "Sales" ("Id") ON DELETE CASCADE;

ALTER TABLE "SaleReturns" ADD CONSTRAINT "FK_SaleReturns_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE RESTRICT;

ALTER TABLE "StockAdjustmentItems" ADD CONSTRAINT "FK_StockAdjustmentItems_StockAdjustments_StockAdjustmentId" FOREIGN KEY ("StockAdjustmentId") REFERENCES "StockAdjustments" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockAdjustments" ADD CONSTRAINT "FK_StockAdjustments_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockAdjustments" ADD CONSTRAINT "FK_StockAdjustments_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockLevels" ADD CONSTRAINT "FK_StockLevels_WarehouseZones_WarehouseZoneId" FOREIGN KEY ("WarehouseZoneId") REFERENCES "WarehouseZones" ("Id") ON DELETE SET NULL;

ALTER TABLE "StockLevels" ADD CONSTRAINT "FK_StockLevels_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockTransferItems" ADD CONSTRAINT "FK_StockTransferItems_StockTransfers_StockTransferId" FOREIGN KEY ("StockTransferId") REFERENCES "StockTransfers" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockTransfers" ADD CONSTRAINT "FK_StockTransfers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockTransfers" ADD CONSTRAINT "FK_StockTransfers_Warehouses_FromWarehouseId" FOREIGN KEY ("FromWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE;

ALTER TABLE "StockTransfers" ADD CONSTRAINT "FK_StockTransfers_Warehouses_ToWarehouseId" FOREIGN KEY ("ToWarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE;

ALTER TABLE "Subscriptions" ADD CONSTRAINT "FK_Subscriptions_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "SupplierProducts" ADD CONSTRAINT "FK_SupplierProducts_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE CASCADE;

ALTER TABLE "Suppliers" ADD CONSTRAINT "FK_Suppliers_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "SystemSettings" ADD CONSTRAINT "FK_SystemSettings_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "TaxConfigurations" ADD CONSTRAINT "FK_TaxConfigurations_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "TaxGroups" ADD CONSTRAINT "FK_TaxGroups_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE CASCADE;

ALTER TABLE "Tenants" ADD CONSTRAINT "FK_Tenants_Warehouses_DefaultWarehouseId1" FOREIGN KEY ("DefaultWarehouseId1") REFERENCES "Warehouses" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217184111_InitialCreate', '9.0.0');

COMMIT;

